[package]
name = "tunnel-server"
version = "5.0.0"
edition = "2024"

[dependencies]
# utilities
anyhow = { workspace = true }
aes-gcm = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-log = { workspace = true }

# Asynchronous runtime
tokio-rustls = { workspace = true }
tokio = { workspace = true }

# channel
flume = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }